-- NEGDI-руу үүсгэсэн бүх захиалга.
-- tranid нь NEGDI-ийн өгсөн өвөрмөц ID. checkid нь зөв ажиллахын тулд тэр захиалгад хамаатай secret.

CREATE TABLE payment_orders (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  tranid          NUMBER NOT NULL UNIQUE,
  checkid         VARCHAR2(64) NOT NULL,
  customer_id     VARCHAR2(64) NOT NULL,
  ordertype       VARCHAR2(32) NOT NULL,
  amount          NUMBER(12, 2) NOT NULL,
  currency        VARCHAR2(3) DEFAULT 'MNT' NOT NULL,
  ordernum        VARCHAR2(20),
  description     VARCHAR2(255),
  status          VARCHAR2(32) NOT NULL,
  approval_code   VARCHAR2(16),
  payment_method  VARCHAR2(16),     -- 'Card' | 'QR'
  bankname        VARCHAR2(16),
  brand           VARCHAR2(16),
  masked_pan      VARCHAR2(32),
  tokenid         NUMBER,
  return_url      VARCHAR2(255),
  negdiurl        VARCHAR2(500),
  regtime         TIMESTAMP,
  last_inquiry_at TIMESTAMP,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_orders_ordertype CHECK (ordertype IN
    ('3dsOrder','Non3dsOrder','Non3dsPayment','3dsPayment','QPAY'))
);

CREATE INDEX ix_payment_orders_customer ON payment_orders (customer_id);
CREATE INDEX ix_payment_orders_status ON payment_orders (status);
CREATE INDEX ix_payment_orders_created ON payment_orders (created_at);

COMMIT;
