-- NEGDI-тэй хийсэн бүх API call-ын audit log (request + response + signature шалгалт).
-- Debug + дахин шалгалт + чанарын хяналтад зориулсан.

CREATE TABLE payment_events (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  tranid          NUMBER,
  endpoint        VARCHAR2(16) NOT NULL,   -- 'ec1000','ec1001','ec1002',...
  direction       VARCHAR2(8) NOT NULL,    -- 'out' | 'in'
  payload         CLOB,                    -- JSON request эсвэл response
  http_status     NUMBER,
  signature_valid NUMBER(1),               -- response үед signature шалгалтын үр дүн
  error           VARCHAR2(500),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_events_direction CHECK (direction IN ('out','in'))
);

CREATE INDEX ix_events_tranid ON payment_events (tranid);
CREATE INDEX ix_events_created ON payment_events (created_at);

COMMIT;
